### ISSUE TITLE
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded

### ISSUE THREAD

**Issue by suocean16** [ultrasev/stream-whisper#13]
服务器在运行时，总是报这个错误。 
似乎是 服务器也需要 cuda ？
这个在 requirement.txt 里面似乎没有。 
我尝试自己 安装，但是不太确定自己是否能解决。 

(py310) root@autodl-container-a62d4480bf-a8c3ae0a:~/autodl-tmp/whisper_osu/stream-whisper# python -m src.server

INFO:root:Model loaded
INFO:faster_whisper:Processing audio with duration 00:17.130
Traceback (most recent call last):
  File "/root/miniconda3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/whisper_osu/stream-whisper/src/server.py", line 62, in <module>
    asyncio.run(main())
  File "/root/miniconda3/envs/py310/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/autodl-tmp/whisper_osu/stream-whisper/src/server.py", line 58, in main
    await asyncio.gather(transcribe())
  File "/root/autodl-tmp/whisper_osu/stream-whisper/src/server.py", line 51, in transcribe
    text, _period = await asyncformer(b_transcribe)
  File "/root/autodl-tmp/whisper_osu/stream-whisper/src/utils.py", line 10, in asyncformer
    return await loop.run_in_executor(pool, sync_func, *args, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/autodl-tmp/whisper_osu/stream-whisper/src/server.py", line 26, in b_transcribe
    segments, info = model.transcribe("chunk.mp3",
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 344, in transcribe
    encoder_output = self.encode(segment)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 767, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded
(py310) root@autodl-container-a62d4480bf-a8c3ae0a:~/autodl-tmp/whisper_osu/stream-whisper#

**Comment by ultrasev** [comment]
@suocean16 确定一下系统是否成功安装 CUDA 并能运行，https://zhuanlan.zhihu.com/p/403438857 
Colab 的 ubuntu 22 应该没有这个问题。

**Comment by suocean16** [comment]
我更换了  cuda 12 版本。 就解决了。 多谢！
